services:
  api:
    ports:
      - "8085:8085"
    image: "kuchnowskip/doryw-backend:1.0"
    environment:
      ACTIVE_PROFILE: "prod"
      DATABASE_URL: "jdbc:postgresql://<IP_SERWERA_BAZY_DANYCH>:5432/doryw"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "doryw0215"
      MAIL_HOST: "<ADRES_SERWERA_MAILINGOWEGO>"
      MAIL_PORT: "<PORT_SERWERA_MAILINGOWEGO>"
      MAIL_USERNAME: "<ADRES_EMAIL_SLUZACY_DO_WYSYLANIA_WIADOMOSCI>"
      MAIL_PASSWORD: "<HASLO_DO_KONTA_EMAIL>"
      CONTAINER_ADDRESS: "0.0.0.0"
      CONTAINER_PORT: "8085"
      JWT_ACCESS_TOKEN_VALIDITY: "3600"
      JWT_REFRESH_TOKEN_VALIDITY: "86400"
      JWT_SECRET: "<KLUCZ_JWT>"
      CORS_ALLOWED_ORIGIN: "<ADRES_APLIKACJI_FRONTENDOWEJ>"

  frontend:
    ports:
      - "3000:80"
    image: "kuchnowskip/doryw-frontend:1.1"
    environment:
      REACT_APP_BASE_URL: "<ADRES_SERWERA_APLIKACJI_BACKENDOWEJ>"

  database:
    ports:
      - "5432:5432"
    image: "postgres:16.4"
    environment:
      POSTGRES_PASSWORD: "doryw0215"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "doryw"
